- name: Redis Server installation playbook
  hosts: dbservers
  user: ansible
  gather_facts: no
  roles:
  - role: linux-user-check
    user: redis
    uid:  1010
    group:  redis
    gid:  1011
    tags: luc

  - role: redis-db-installation

#  - role: redis-db-installation
#    db_name:  hipchat
#    db_user:  hipchat
#    db_user_password: hichat123
#    tags: rdi

